### ISSUE TITLE
Move Website to master branch

### ISSUE THREAD

**Issue by stefnotch** [mgatelabs/GenshinSolvers#55]
At this point, the website has been developed much further than the Java application. Would it be reasonable to move it to the master branch (and move the Java application to a different branch)?

Also, there is an option to set a website for a repository when you go to [https://github.com/mgatelabs/GenshinSolvers](https://github.com/mgatelabs/GenshinSolvers) and click on the cog in the top right.

![image](https://user-images.githubusercontent.com/10220080/156309735-62bcf47b-bea0-4919-9d8d-bdebb67abd64.png)

**Comment by mgatelabs** [comment]
I will do this, and apply the dev changes to it

**Comment by mgatelabs** [comment]
Pages is now the main branch.  Pages-Dev has been merged in / deleted.  A new Pages-Dev has been created.

**Comment by stefnotch** [comment]
Awesome!

**Comment by mgatelabs** [comment]
Switching to Pages-Dev-2 as dev branch, but I should make one for each issue and do pulls
